# adapted from https://github.com/lm-sys/llm-decontaminator/blob/main/detect_instruct.py

system: ""

user: |-
  Help me determine if the following two planning tasks in given are the same (just paraphrased).

  First planning task: {problem1}
  Second planning task: {problem2}

  Disregard the names and minor changes in word order that appear within.
  
  If the two tasks are very similar (paraphrased) and if they produce the same answer in corresponding conditions, we consider them to be the same task.

  Think step by step and respond with "True" (tasks are the same) or "False" (tasks are different). Do not respond with anything else.
